class Jugador {
    + moverArriba()
    + moverAbajo()
    + moverDerecha()
    + moverIzquierda()
    + saltar()
}

class Mascara {
    + activar()
    + desactivar()
}

class Moneda {
    + recolectar()
}

class Obstaculo {
    + colisionar()
}

class Poder {
    + usar()
}

class Nivel {
    + cargar()
    + iniciar()
    + completar()
    + generarObstaculos()
}

class Juego {
    + iniciar()
    + pausar()
    + reiniciar()
    + terminar()
}



Jugador "1" o-- "1" Mascara
Jugador "1" *-- "*" Moneda
Jugador "1" o-- "1" Poder

Juego "1" *-- "*" Nivel
Nivel "1" *-- "*" Obstaculo

Mascara -- Moneda
Mascara -- Obstaculo

